# Plugins
gems: [jekyll-sitemap]
safe: false

# Build Settings
markdown: kramdown
redcarpet:
  extensions: ["tables"]
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Denis Ivanov"
email: "denis@ivanovdenis.ru"
github:
  url: http://dev.ivanovdenis.ru
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-62226812-1"
googleAnalyticsSiteUrl: "auto"
googleSiteVerification: "RwWVPu3LqA08EEymfN9D3UNRGLqV7nxI-JT0ebLMKt8"
yandexMertikaTrackingId: "31748171"
yandexSiteVerification: "6f247985ca8917c1"

# Head
metaKeywords: "denis, ivanov, personal, blog, dotnet, ddd, domain, driven, design, reactive, cqrs, 2gis, subaru, .net, software, technologies"
twitterAccount: "@denisivanov"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/about/", text: "About me"}
bottomNavigationLinks:
 - {link: "https://github.com/denisivan0v/feedback/issues/new", text: "Ask me a question"}
rightNavigationButtons:
 - {link: "https://github.com/denisivan0v/feedback/issues/new", text: "Ask me a question"}

# Hero Block
heroImage: "road-split.jpg"
heroTitle: "Software Engineering And <typeout>"
eventDate: "Denis Ivanov's Blog"
typeoutTextValues: '"Technologies", ".NET", "Open Source", "DDD", "Rx"'
typeoutFallback: "Technologies"
heroButtons:
  - {permalink: "/#latest-news", text: "Continue reading"}

# About Block
aboutTitle: "Who Am I?"
aboutBlock:
 - {title: "Software dev", image: "dotnet.jpg", text: "Usually I am using .NET to build software" }
 - {title: "Microsoft MVP", image: "mvp.png", text: "MVP in .NET since 2015" }
 - {title: "Working for 2GIS", image: "2gis.png", text: "Designing and developing some of the company's systems. Also running a team there." }
 

# Latest News Block
latestNewsTitle: "Latest posts"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterUserName: "denisivanov"
twitterFeed: "https://twitter.com/denisivanov"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Contact me"
subscribeRedirectTitle: "Leave a message"
subscribeAction: "https://github.com/denisivan0v/feedback/issues/new"
subscribeInfo: "I will try to answer as soon as possible. Stay tuned!"

# Footer
socialLinks:
 - {link: "https://plus.google.com/113159328736283972698", icon: "google-plus"}
 - {link: "https://twitter.com/denisivanov", icon: "twitter"}
 - {link: "https://facebook.com/ivanovdenis.ru", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {permalink: "/about/", text: "About me"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:denis@ivanovdenis.ru", text: "denis[at]ivanovdenis[dot]ru"}

# Blog
blogTitle: "Latest posts"
blogCommentsEnabled: true
discusShortName: "denisivan0v"
